version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - rowserrcheck # SQL
    - sqlclosecheck # SQL
    - cyclop # duplicate of gocyclo
    - wsl # Deprecated
    - err113
    - exhaustive
    - exhaustruct
    - lll
    - mnd
    - noinlineerr
    - paralleltest
    - prealloc
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck

  settings:
    funlen:
      lines: -1
      statements: 50
    godox:
      keywords:
        - FIXME
    gocyclo:
      min-complexity: 12
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    tagliatelle:
      case:
        rules:
          json: snake

  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
